#+TITLE: dotfiles for macOS
#+OPTIONS: toc:nil num:nil ^:nil
#+STARTUP: showall

In addition to the base =README.org= file, this document describes and
creates macOS specific configuration.

* macOS Junk

  =defaults write com.apple.Accessibility ReduceMotionEnabled -bool true=

  Set hostname:

  #+begin_src sh
    sudo scutil --set HostName ${HOSTNAME}
  #+end_src

* Dark & Light Theme
   :PROPERTIES:
   :header-args: :tangle ~/.bashrc.d/200-macos-theme.bash
   :END:

  #+begin_src sh
    function k20e_macos_is_dark() {
        [[ $(osascript -e 'tell application "System Events" to tell appearance preferences to return dark mode') = 'true' ]]
    }

    function k20e_alacritty_set_theme() {
        if k20e_macos_is_dark; then
            sed -i '' -e 's/light\.yaml/dark\.yaml/' ${HOME}/.config/alacritty/alacritty.yml
        else
            sed -i '' -e 's/dark\.yaml/light\.yaml/' ${HOME}/.config/alacritty/alacritty.yml
        fi
    }
  #+end_src

* Environment Variables
   :PROPERTIES:
   :header-args: :tangle ~/.bashrc.d/010-macos-env.bash
   :END:

  #+begin_src sh
    export SHELL=/opt/homebrew/bin/bash
  #+end_src

* [[https://brew.sh/][Homebrew]]

  =brew= doesn't have a great way to manage dependencies that I've
  found outside of a =Brewfile= and the =bundle= subcommand.

** Configuration & Environment
   :PROPERTIES:
   :header-args: :tangle ~/.bashrc.d/050-homebrew-env.bash
   :END:

   #+BEGIN_SRC sh
     export HOMEBREW_CASK_OPTS=--require-sha
     export HOMEBREW_NO_ANALYTICS=1
     export HOMEBREW_NO_INSECURE_REDIRECT=1

     # [ -e /opt/homebrew/etc/bash_completion.d/brew ] && source /opt/homebrew/etc/bash_completion.d/brew
   #+END_SRC

** [[https://github.com/Homebrew/homebrew-bundle][Bundle]]

   Install:

   #+BEGIN_SRC sh
     brew tap Homebrew/bundle
   #+END_SRC

   Programs currently installed by =brew= can be dumped to a global
   =Brewfile=, which defaults to =${HOME}/.Brewfile=:

   #+BEGIN_SRC sh
     brew bundle dump --force --global --verbose
   #+END_SRC

   Install all programs specified in the global =${HOME}./Brewfile=:

   #+BEGIN_SRC sh
     brew bundle --global
   #+END_SRC

** =${HOME}/.Brewfile=
   :PROPERTIES:
   :CUSTOM_ID: brewfile
   :header-args: :tangle ~/.Brewfile
   :END:

   #+BEGIN_SRC sh
     tap "buo/cask-upgrade"
     tap "d12frosted/emacs-plus"
     tap "homebrew/aliases"
     tap "homebrew/autoupdate"
     tap "homebrew/bundle"
     tap "homebrew/command-not-found"
     tap "homebrew/services"
     tap "homebrew/test-bot"
     tap "jmespath/jmespath"
     tap "tidbyt/tidbyt"
     brew "automake"
     brew "libyaml"
     brew "asdf"
     brew "aspell"
     brew "bash"
     brew "bash-completion@2"
     brew "bison"
     brew "chafa"
     brew "cmake"
     brew "dasel"
     brew "diff-so-fancy"
     brew "difftastic"
     brew "eza"
     brew "libssh"
     brew "xvid"
     brew "ffmpeg"
     brew "flex"
     brew "flyctl"
     brew "gawk"
     brew "gcc"
     brew "gd"
     brew "gflags"
     brew "git"
     brew "gnupg"
     brew "go"
     brew "gprof2dot"
     brew "hunspell"
     brew "shared-mime-info"
     brew "imagemagick"
     brew "innoextract"
     brew "ispell"
     brew "oniguruma"
     brew "jq"
     brew "kubernetes-cli"
     brew "less"
     brew "libdvdcss"
     brew "makedepend"
     brew "node"
     brew "parallel"
     brew "perl"
     brew "pre-commit"
     brew "pstree"
     brew "pv"
     brew "pyenv"
     brew "pyenv-virtualenv"
     brew "python@3.10"
     brew "repo"
     brew "ripgrep"
     brew "rocksdb"
     brew "ruby", link: true
     brew "scons"
     brew "shellcheck"
     brew "sk"
     brew "starship"
     brew "subversion"
     brew "terminal-notifier"
     brew "texi2html"
     brew "tree"
     brew "watch"
     brew "wget"
     brew "yamllint"
     brew "yasm"
     brew "d12frosted/emacs-plus/emacs-plus@29"
     brew "jmespath/jmespath/jp"
     brew "tidbyt/tidbyt/pixlet"
     cask "1password"
     cask "1password-cli"
     cask "alfred"
     cask "alt-tab"
     cask "android-platform-tools"
     cask "betterdisplay"
     cask "firefox"
     cask "google-drive"
     cask "istat-menus"
     cask "mactex-no-gui"
     cask "opal-composer"
     cask "openemu"
     cask "orion"
     cask "podman-desktop"
     cask "qlmarkdown"
     cask "rectangle"
     cask "slack"
     cask "tomatobar"
     cask "transmission"
     cask "via"
     cask "vlc"
     cask "wezterm"
     cask "zoom"
   #+END_SRC

** [[https://github.com/mas-cli/mas][mas]]

   #+BEGIN_QUOTE
   A simple command line interface for the Mac App Store. Designed for
   scripting and automation.
   #+END_QUOTE

   The =Bundlefile= above should install the App Store programs listed
   with in it using =mas=.
